name: tripto_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  shared_preferences: ^2.3.1
  dio: ^5.5.0+1
  shimmer: ^3.0.0
  webview_flutter: ^4.10.0
  carousel_slider: ^5.0.0
  url_launcher: ^6.3.0
  flutter_secure_storage: ^9.2.2
  expandable_text: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.1
  flutter_custom_clippers: ^2.1.0
  flutter_screenutil: ^5.9.3
  animate_do: ^3.3.9
  smooth_page_indicator: ^1.2.0+3
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.1
  vibration: ^2.0.1
  json_annotation: ^4.9.0
  flutter_rating_bar: ^4.0.1
  uuid: ^4.5.1
  flutter_spinkit: ^5.2.1
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/TripTo.png
    - assets/images/TripTo2.png
    - assets/images/firstbanner.jpg
    - assets/images/secondbanner.jpg
    - assets/images/thirdbanner.jpg
    - assets/images/fourthbanner.jpg
    - assets/images/success.png

  fonts:
    - family: irs
      fonts:
        - asset: assets/fonts/IRANSansWeb_Bold.ttf
